### ISSUE TITLE
Lock button not orange and wrong icon

### ISSUE THREAD

**Issue by algorythm** [hold17/cphindustries#2]
Look at 3 on the image:

![edit back](https://user-images.githubusercontent.com/5315872/33388406-2ad957b0-d530-11e7-8318-7d4d50d74151.png)

Lock button not orange.

**Comment by algorythm** [comment]
Sorry to be annoying, but it's still wrong. When viewing items, it should be gray. Only in the edit fragments it should be orange. That's at least how we did it in Sketch...

**Comment by algorythm** [comment]
I like the color though, but it's nice to get a visual feedback when tapping the button

**Comment by Okjonas** [comment]
I think "Plus fab" button should be green

**Comment by Okjonas** [comment]
Prototype fab button
<img width="170" alt="screen shot 2018-01-14 at 21 32 08" src="https://user-images.githubusercontent.com/16692164/34920405-74a77050-f972-11e7-9f6f-f50eef47e61c.png">

I like that color
