### ISSUE TITLE
Implement create scenes

### ISSUE THREAD

**Issue by algorythm** [hold17/cphindustries#26]
Branch: [feature/implement_create_scenes](/hold17/cphindustries/tree/feature/implement_create_scenes).

**Comment by awo-dev** [comment]
Branch: `feature/implement_create_scenes`

**Comment by algorythm** [comment]
When a new `Scene` has been added, the app crashes when loading the list of `Scene`s.

**Comment by algorythm** [comment]
Issue blocked by #37. Cannot proceed until That issue is resolved.
