### ISSUE TITLE
Show version number when opening app

### ISSUE THREAD

**Issue by algorythm** [hold17/cphindustries#28]
It should be possible to see the version of the app somewhere, preferably when loading the app and / or on the first view.

**Comment by tlien** [comment]
Could be implemented as a splash-screen on startup, showing the Copenhagen Industries logo in the middle with a version number underneath.

**Comment by algorythm** [comment]
Splash-screen could be associated with #34.

**Comment by algorythm** [comment]
Version number should be shown in settings instead.

**Comment by tlien** [comment]
Completed in Issue #47, implemented as "About" entry in action menu.
