### ISSUE TITLE
DTO's should include its parent object

### ISSUE THREAD

**Issue by algorythm** [hold17/cphindustries#51]
i.e. a `Shoot` should have a reference to its parent `Scene` and a `Weapon` should contain a list of `Shoot`s.

Implement for
* [x] Shoot
* [x] Weapon

**Comment by Okjonas** [comment]
We did not implement the parent object in the DTO's because it conflicts with the JSON object. 

Instead, the shootDTO has a scene id and the lists from SceneDTO and ShootDTO are removed.

The correlation between weapon and shoot are now in the ShootWeaponDTO.
